server:
  port: 8081

spring:
  application:
    name: candidate-service

  data:
    mongodb:
      database: shortlist-test
      port: 27017
      host: localhost

eureka:
  client:
    serviceUrl:
      defualtZone: http://localhost:8761/eureka