server:
  port: 8080

spring:
  application:
    name: employer-service

  datasource:
    url: jdbc:mysql://localhost:3306/shortlist
    username: mysql-user
    password: mysqlUser

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
        id:
          new_generator_mappings: false